pipeline {
  agent any
  
  stages{
    stage("build"){
      steps{
        echo 'clean'
        mvn clean
      }
    }
    stage("package"){
    steps{
      echo 'testing'
      mvn package
    }
    }
    stage("test"){
    steps{
      echo 'testing'
      mvn test
    }
    }
    stage("deploy"){
    steps{
      echo 'install'
      mvn install
    }
    }
  }

}
