pipeline {
    
  agent any
  
  tools {
      maven 'Maven'
  }
  
  stages{
    stage("build"){
      steps{
        git 'https://github.com/nitinjmv/jenkins-jdk8/'
        sh "mvn clean"
      }
    }
    stage("package"){
    steps{
      sh "mvn package"
    }
    }
    stage("test"){
    steps{
      sh "mvn test"
    }
    }
    stage("deploy"){
    steps{
      sh "mvn install"
    }
    }
  }

}
